name: 'Build'

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MIN: 3

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup git user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Setup release branch
        run: |
          export BRANCH_NAME=release
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_ENV"
          git checkout -b $BRANCH_NAME origin/$BRANCH_NAME

      - name: Merge changes
        run: |
          git merge --no-commit main

      - name: Run install
        run: |
          yarn install

      - name: Build production bundle
        run: |
          yarn build

      - name: Create commit
        run: |
          git add .
          git commit --allow-empty -m "chore(build): production build"

      - name: Push changes on git
        run: |
          git push --set-upstream origin ${{ env.branch_name }}
