name: 'Build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  SEGMENT_DOWNLOAD_TIMEOUT_MIN: 3

jobs:
  files-changed:
    name: 'Detect file changes'

    runs-on: ubuntu-latest
    timeout-minutes: 3

    outputs:
      node: ${{ steps.changes.outputs.node }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  build:
    needs: files-changed
    if: needs.files-changed.outputs.node == 'true'

    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup release branch
        run: |
          export BRANCH_NAME=release
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_ENV"

          git fetch origin
          git checkout -b $BRANCH_NAME
          git merge --no-commit main
          git add .

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build"
